In [1]:
#import dependencies
import pandas as pd

In [2]:
#Read in povery data from CSV
performance_df = pd.read_csv("data/california_hospitals_performance_ratings.csv", header=0, encoding='cp1252')
performance_df.head()

,Year,County,Hospital,OSHPDID,system,Type of Report,Performance Measure,# of Adverse Events,# of Cases,Risk-adjusted Rate,Hospital Ratings,Longitude,Latitude
0,2016,Alameda,Alameda Hospital,106010735,Alameda Health System,IMI,AMI,3.0,17.0,16.1,As Expected,-122.253,37.76266
1,2016,Alameda,Alameda Hospital,106010735,Alameda Health System,IMI,Acute Stroke,9.0,74.0,23.6,Worse,-122.253,37.76266
2,2016,Alameda,Alameda Hospital,106010735,Alameda Health System,IMI,Acute Stroke Hemorrhagic,5.0,9.0,48.9,Worse,-122.253,37.76266
3,2016,Alameda,Alameda Hospital,106010735,Alameda Health System,IMI,Acute Stroke Ischemic,4.0,65.0,15.2,As Expected,-122.253,37.76266
4,2016,Alameda,Alameda Hospital,106010735,Alameda Health System,IMI,Acute Stroke Subarachnoid,NaN,NaN,NaN,NaN,-122.253,37.76266

In [3]:
#Remove unnecessary columns
clean_df=performance_df.drop(columns=["OSHPDID","system", "Type of Report"])
clean_df.head()

,Year,County,Hospital,Performance Measure,# of Adverse Events,# of Cases,Risk-adjusted Rate,Hospital Ratings,Longitude,Latitude
0,2016,Alameda,Alameda Hospital,AMI,3.0,17.0,16.1,As Expected,-122.253,37.76266
1,2016,Alameda,Alameda Hospital,Acute Stroke,9.0,74.0,23.6,Worse,-122.253,37.76266
2,2016,Alameda,Alameda Hospital,Acute Stroke Hemorrhagic,5.0,9.0,48.9,Worse,-122.253,37.76266
3,2016,Alameda,Alameda Hospital,Acute Stroke Ischemic,4.0,65.0,15.2,As Expected,-122.253,37.76266
4,2016,Alameda,Alameda Hospital,Acute Stroke Subarachnoid,NaN,NaN,NaN,NaN,-122.253,37.76266

In [4]:
#Count performance measures by year, county, and hospital ratings
counties_df=clean_df.groupby(["Year","County","Hospital Ratings"]).count()["Performance Measure"]
counties_df.head(10)

Year  County     Hospital Ratings
2016  Alameda    As Expected         116
                 Better                2
                 Worse                 7
      Amador     As Expected           7
                 Worse                 1
      Butte      As Expected          30
                 Better                2
                 Worse                 1
      Calaveras  As Expected           7
      Colusa     As Expected           2
Name: Performance Measure, dtype: int64

In [5]:
#hospitals_df=clean_df.groupby(["Year","County","Hospital"]).count()["OSHPDID"]
#hospitals_df.head(30)
#hospitals_df=clean_df.groupby(["Year", "County"])['Hospital'].value_counts()
#hospitals_df.head(30)

In [6]:
#Count adverse events by year, county, and hospital ratings
adverse_df=clean_df.groupby(["Year","County","Hospital Ratings"]).sum()["# of Adverse Events"]
adverse_df.head(10)

Year  County     Hospital Ratings
2016  Alameda    As Expected         730.0
                 Better               20.0
                 Worse                63.0
      Amador     As Expected          13.0
                 Worse                 6.0
      Butte      As Expected         164.0
                 Better                5.0
                 Worse                31.0
      Calaveras  As Expected           5.0
      Colusa     As Expected           1.0
Name: # of Adverse Events, dtype: float64

In [7]:
#Count number of cases by year, county, and hospital ratings
cases_df=clean_df.groupby(["Year","County","Hospital Ratings"]).sum()["# of Cases"]
cases_df.head(10)

Year  County     Hospital Ratings
2016  Alameda    As Expected         16051.0
                 Better                353.0
                 Worse                 792.0
      Amador     As Expected           333.0
                 Worse                  62.0
      Butte      As Expected          4125.0
                 Better                628.0
                 Worse                 389.0
      Calaveras  As Expected           155.0
      Colusa     As Expected             7.0
Name: # of Cases, dtype: float64

In [8]:
#Create new df
performance_summary_df = pd.DataFrame()

performance_summary_df["Hospital Ratings Total"] = counties_df
performance_summary_df["Total Number of Adverse Events"]= adverse_df
performance_summary_df["Total Number of Cases"]= cases_df

performance_summary_df

                               Hospital Ratings Total  \
Year County  Hospital Ratings
2016 Alameda As Expected                          116
             Better                                 2
             Worse                                  7
     Amador  As Expected                            7
             Worse                                  1
...                                               ...
2020 Ventura As Expected                           67
             Better                                 5
     Yolo    As Expected                           14
             Worse                                  1
     Yuba    As Expected                           12

                               Total Number of Adverse Events  \
Year County  Hospital Ratings
2016 Alameda As Expected                                730.0
             Better                                      20.0
             Worse                                       63.0
     Amador  As Expected                                 13.0
             Worse                                        6.0
...                                                       ...
2020 Ventura As Expected                                352.0
             Better                                      57.0
     Yolo    As Expected                                 31.0
             Worse                                        3.0
     Yuba    As Expected                                 98.0

                               Total Number of Cases
Year County  Hospital Ratings
2016 Alameda As Expected                     16051.0
             Better                            353.0
             Worse                             792.0
     Amador  As Expected                       333.0
             Worse                              62.0
...                                              ...
2020 Ventura As Expected                      8429.0
             Better                           1647.0
     Yolo    As Expected                       773.0
             Worse                              55.0
     Yuba    As Expected                      2547.0

[518 rows x 3 columns]

In [9]:
performance_summary_df.to_csv('performance_summary.csv')